spring:
    cloud:
        gateway:
            server:
                webmvc:
                    routes:
                        - id: wallet-service
                          uri: lb://WALLET-SERVICE
                          predicates:
                              - Path=/api/auth/**, /api/wallets/**
                          filters:
                              - CircuitBreaker=walletCB

                        - id: shop-service
                          uri: lb://SHOP-SERVICE
                          predicates:
                              - Path=/api/orders/**, /api/cart/**
                          filters:
                              - CircuitBreaker=shopCB

                        - id: inventory-internal
                          uri: lb://INVENTORY-SERVICE
                          predicates:
                              - Path=/internal/inventory/**, /api/products/**
                          filters:
                              - CircuitBreaker=inventoryCB

resilience4j:
    circuitbreaker:
        configs:
            default:
                slidingWindowSize: 10
                failureRateThreshold: 50
                waitDurationInOpenState: 5s
                permittedNumberOfCallsInHalfOpenState: 3
                recordEvents: true
        instances:
            walletCB:
                baseConfig: default
            shopCB:
                baseConfig: default
            inventoryCB:
                baseConfig: default
                failureRateThreshold: 30

management:
    endpoints:
        web:
            exposure:
                include: health,circuitbreakers,resilience4j,metrics,gateway
    endpoint:
        health:
            show-details: always
            validate-group-membership: false
            group:
                circuitbreakers:
                    include: walletCB,shopCB,inventoryCB
    health:
        circuitbreakers:
            enabled: true
