internal:
    api:
        secret: 97c18ccf-0d5d-4348-97d2-ca01258c4232 # WARN: MUST BE IN ENVIRONMENT VARIABLE

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
