internal:
    api:
        secret: 80cb285b13dc312e2f071c23257580b49ca6b57bb1f9403040904b3c1844b4d5 # WARN: MUST BE IN ENVIRONMENT VARIABLE

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

jwt:
    # A 256-bit key (32 bytes) encoded in Base64.
    secret: O75yzG8C1iF9QkCzFBKxhHi4kWcaGIt/Qm0kFxkkqeE= # WARN: MUST BE IN ENVIRONMENT VARIABLE
    # Token expiration time in milliseconds (24 hours)
    expiration: 86400000
    service-expiration: 300000 # 5 minutes for services

app:
    security:
        token-refresh-buffer: 120 # in seconds
