spring.application.name=naming-server
server.port= 8761

# i am the server not a client, i don't need to register myself with myself
eureka.client.register-with-eureka = false

# i already have the registry i don't need to go and fetch it 
eureka.client.fetch-registry = false

# this is a dev setup to only show alive services and not stop killing dead services / just to avoid problems
euraka.server.enable-self-preservation = false
