server:
    port: 8888

spring:
    application:
        name: config-server
    profiles:
        active: native # ← Enables native (filesystem) backend
    cloud:
        config:
            server:
                native:
                    search-locations:
                        - file:./config-dir # Relative to project root

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true
